import mongoose from "mongoose";

const UserSchema = mongoose.Schema({
  id: { type: Number, unique: true },
  account_id: { type: String },
  account_details_status: { type: String },
  type: { type: String, enum: ["CUSTOMER", "DRIVER"], required: true },
  first_name: { type: String, required: true, trim: true },
  last_name: { type: String, required: true, trim: true },
  contact_number: { type: String },
  mobile_with_code: { type: String },
  email: { type: String },
  password: { type: String },
  image: { type: String },
  location: {
    type: { type: String, enum: ["Point"], default: "Point" },
    coordinates: { type: [Number], default: [0, 0] },
  },
  lat: { type: String },
  lng: { type: String },
  fcm_token: { type: String },
  country_id: { type: String },
  state_id: { type: String },
  state_name: { type: String },
  city_id: { type: String },
  city_name: { type: String },
  social_id: { type: String },
  gender: { type: String },
  wallet: { type: Number },
  earn_points: { type: Number },
  referal_points: { type: Number },
  booking_points: { type: Number },
  referral_code: { type: String },
  signup_referral_code: { type: String },
  register_id: { type: String },
  ios_register_id: { type: String },
  status: { type: String },
  approve_status: { type: String },
  available_status: { type: String },
  code: { type: String },
  note: { type: String },
  note_block: { type: String },
  block_unblock: { type: String },
  remove_status: { type: String },

  verify: { type: String, default: "NO" },
  date_time: { type: String },
  // OTP fields
  otpHash: { type: String },
  otpExpires: { type: Date },
});

export default mongoose.model("user", UserSchema);
